### ISSUE TITLE
Please add support for utf8-string 1.x

### ISSUE THREAD

**Issue by peti** [dsorokin/aivika-experiment#2]
We would like to update NixOS to the latest version of utf8-string, but unfortunately your package doesn't compile against the new version. Is there any chance of getting a quick update to remedy that issue?

**Comment by dsorokin** [comment]
Thanks for informing me. I study the issue. I'll try to update the package.

**Comment by dsorokin** [comment]
Done. I removed the dependency from this package as GHC supports UTF8 now.

**Comment by peti** [comment]
Can I find the new version on Hackage?

**Comment by dsorokin** [comment]
Yes, I uploaded it. The packages have number 3.1 (except for aivika-transformers that I did not update).

**Comment by peti** [comment]
Thank you!
